# ================================
# アプリケーション設定
# ================================
spring.application.name=api
server.port=8080

# ================================
# DB接続設定（PostgreSQL）
# spring.datasource.url=jdbc:postgresql://db:5432/mydb
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d1cna88dl3ps73fefdug-a:5432/mydb_scrx
spring.datasource.username=toki_user
spring.datasource.password=qE1I8zaPh41h8UgpRYm4qnNsQHR2NC8G
spring.datasource.driver-class-name=org.postgresql.Driver



# --- JPAの設定（必要に応じて） ---
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.security.debug=true

# --- JPA設定 ---
# spring.jpa.hibernate.ddl-auto=update
# spring.security.debug=true
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.default_schema=evaluation
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=evaluation


# SQLログ出力設定
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.security.debug=true

# JWT設定
# jwt.secret=your_super_secure_secret_key_456789!

# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# spring.security.debug=true

# JWT設定
jwt.secret=VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLUpXVC0yMDI1IQ==

# ================================
# メール設定（Mailpit用）
# ================================
spring.mail.from=no-reply@example.com

# Mailpit用SMTP設定
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ================================
# フロントエンド連携設定
# ================================
# app.frontend.url=http://localhost:3000

# # app.reset.base-url=http://localhost:3000/reset_password
# # メール送信は、app.reset.base-urlっていう変数を共通化してreset_passwordっていう後ろのURLを処理に組み込む
# # app.reset.base-urlをfront-urlのように
# app.reset.base-url=http://localhost:3000/reset_password

app.frontend.url=https://toki-nishiyama-project-3.onrender.com
app.reset.base-url=https://toki-nishiyama-project-3.onrender.com/reset_password
