
spring.application.name=api

spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# メール送信元
spring.mail.from=no-reply@example.com

# Mailpit用SMTP設定
# Dockerホストにアクセスする場合
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

